name: "document-extraction_main-system"

volumes:
  minio_data: null

services:

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=ROOT
      - MINIO_ROOT_PASSWORD=ROOT1234
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    volumes:
      - minio_data:/data
    command: 
      - server 
      - /data 
      - --console-address 
      - :9001

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml

  alertmanager:
    image: prom/alertmanager:latest
    depends_on:
      - prometheus
    ports:
      - "9093:9093"
    volumes:
      - ./configs/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    entrypoint: ["alertmanager", "--config.file=/etc/alertmanager/alertmanager.yml"]
    
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15692:15692"
    environment:
      - RABITMQ_DEFAULT_USER=ROOT
      - RABITMQ_DEFAULT_PASS=ROOT1234