name: "document-extraction_main-system"

networks:
  redpanda_network:
    driver: bridge

volumes:
  minio_data: null
  redpanda_data: null

services:

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=ROOT
      - MINIO_ROOT_PASSWORD=ROOT1234
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    volumes:
      - minio_data:/data
    command: 
      - server 
      - /data 
      - --console-address 
      - :9001

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  alertmanager:
    image: prom/alertmanager:latest
    depends_on:
      - prometheus
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    entrypoint: ["alertmanager", "--config.file=/etc/alertmanager/alertmanager.yml"]

  redpanda-seed:
    image: redpandadata/redpanda:latest
    deploy:
      replicas: 3
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - redpanda_network
    ports:
      - "18081:18081"
      - "18082:18082"
      - "19092:9092"
      - "19644:9644"
    
  redpanda-node:
    image: redpandadata/redpanda:latest
    volumes:
      - redpanda_data:/var/lib/redpanda/data
  
  redpanda-console:
    image: redpandadata/console:latest
    networks:
      - redpanda_network
    depends_on:
      - redpanda
    ports:
      - "8080:8080"
    volumes:
      - ./redpanda-console-config.yml:/tmp/config.yml
    entrypoint: /app/console
    environment:
      - CONFIG_FILEPATH=/tmp/config.yml


