name: "document-processing"

services:
  # yolov8:
  #   build:
  #     context: ./yolov8
  #   ports:
  #     - "10000:8080"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [gpu]
  #             device_ids: ["0"]
  
  # in21k-classifier:
  #   build:
  #     context: ./image-classifier
  #   ports:
  #     - "10001:8080"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [gpu]
  #             device_ids: ["0"]

  tesseract-server:
    build:
      context: ./tesseract
    ports:
      - "10003:8080"
